#!/usr/bin/env tsx
/**
 * Update lesson PDF and solution URLs from Google Sheets JSON file
 * 
 * Reads the JSON file generated by read-google-sheets.ts
 * and updates the corresponding lessons in Supabase.
 */

import { config } from "dotenv";
import { resolve } from "path";
import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "fs";
import { getSupabaseUrl, getSupabaseServiceRoleKey } from "../src/lib/supabase/env";

config({ path: resolve(process.cwd(), ".env.local") });

interface LessonData {
  slug: string;
  pdf_url: string;
  solution_url: string;
}

interface GoogleSheetsData {
  headers: string[];
  data: LessonData[];
  raw: any[][];
}

async function updateLessonUrlsFromJson(jsonFilePath: string, dryRun: boolean = false) {
  const supabaseUrl = getSupabaseUrl();
  const serviceRoleKey = getSupabaseServiceRoleKey();

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error(
      "Missing Supabase credentials. Set NEXT_PUBLIC_SUPABASE_URL_DEV/PROD and SUPABASE_SERVICE_ROLE_KEY_DEV/PROD"
    );
  }

  const supabase = createClient(supabaseUrl, serviceRoleKey);

  // Read and parse JSON file
  console.log(`\n📖 Reading JSON file: ${jsonFilePath}\n`);
  const jsonContent = readFileSync(jsonFilePath, "utf-8");
  const sheetsData: GoogleSheetsData = JSON.parse(jsonContent);

  if (!sheetsData.data || sheetsData.data.length === 0) {
    throw new Error("No lesson data found in JSON file");
  }

  console.log(`📊 Found ${sheetsData.data.length} lesson(s) in JSON\n`);

  if (dryRun) {
    console.log("🔍 DRY RUN MODE - No changes will be made\n");
  }

  let successCount = 0;
  let notFoundCount = 0;
  let errorCount = 0;
  let alreadyUpToDateCount = 0;
  const notFoundSlugs: string[] = [];
  const errors: Array<{ slug: string; error: string }> = [];

  // Process each lesson
  for (const lessonData of sheetsData.data) {
    const { slug, pdf_url, solution_url } = lessonData;

    if (!slug) {
      console.warn(`⚠️  Skipping row with missing slug`);
      errorCount++;
      continue;
    }

    // Find lesson by slug
    const { data: lesson, error: fetchError } = await supabase
      .from("courses_lessons")
      .select("id, slug, title, pdf_url, solution_url")
      .eq("slug", slug)
      .single();

    if (fetchError || !lesson) {
      console.log(`❌ Lesson not found: ${slug}`);
      notFoundCount++;
      notFoundSlugs.push(slug);
      continue;
    }

    // Check if update is needed
    const needsUpdate = 
      lesson.pdf_url !== pdf_url || 
      lesson.solution_url !== solution_url;

    if (!needsUpdate) {
      if (!dryRun) {
        console.log(`✓ ${slug} - Already up to date`);
        alreadyUpToDateCount++;
      } else {
        console.log(`[DRY RUN] ${slug} - Already up to date`);
      }
      successCount++;
      continue;
    }

    if (dryRun) {
      console.log(`[DRY RUN] Would update: ${slug}`);
      console.log(`  Current pdf_url: ${lesson.pdf_url || "(empty)"}`);
      console.log(`  New pdf_url: ${pdf_url}`);
      console.log(`  Current solution_url: ${lesson.solution_url || "(empty)"}`);
      console.log(`  New solution_url: ${solution_url}\n`);
      successCount++;
      continue;
    }

    // Update lesson
    const { error: updateError } = await supabase
      .from("courses_lessons")
      .update({
        pdf_url: pdf_url || null,
        solution_url: solution_url || null,
      })
      .eq("id", lesson.id);

    if (updateError) {
      console.error(`❌ Failed to update ${slug}: ${updateError.message}`);
      errorCount++;
      errors.push({ slug, error: updateError.message });
    } else {
      console.log(`✅ Updated: ${slug} - ${lesson.title}`);
      successCount++;
    }
  }

  // Summary
  console.log("\n" + "=".repeat(60));
  console.log("📊 SUMMARY");
  console.log("=".repeat(60));
  console.log(`✅ Successfully ${dryRun ? "verified" : "updated"}: ${successCount}`);
  if (!dryRun && alreadyUpToDateCount > 0) {
    console.log(`✓ Already up to date: ${alreadyUpToDateCount}`);
  }
  console.log(`❌ Not found: ${notFoundCount}`);
  console.log(`⚠️  Errors: ${errorCount}`);

  if (notFoundSlugs.length > 0) {
    console.log(`\n⚠️  Lessons not found in database:`);
    notFoundSlugs.forEach((slug) => console.log(`   - ${slug}`));
  }

  if (errors.length > 0) {
    console.log(`\n❌ Errors encountered:`);
    errors.forEach(({ slug, error }) => {
      console.log(`   - ${slug}: ${error}`);
    });
  }

  if (dryRun) {
    console.log(`\n💡 Run without --dry-run to apply changes`);
  }

  console.log();
}

// Main execution
async function main() {
  const args = process.argv.slice(2);

  if (args.includes("--help") || args.includes("-h")) {
    console.log(`
Update Lesson URLs from Google Sheets JSON Script

Usage:
  npx tsx scripts/update-lesson-urls-from-json.ts [json-file-path] [--dry-run]

Arguments:
  [json-file-path]    Path to JSON file (default: scripts/google-sheets-output.json)
  --dry-run           Preview changes without applying them

Example:
  npx tsx scripts/update-lesson-urls-from-json.ts
  npx tsx scripts/update-lesson-urls-from-json.ts scripts/google-sheets-output.json --dry-run
`);
    process.exit(0);
  }

  const jsonFilePath = args.find(arg => !arg.startsWith("--")) || 
    resolve(process.cwd(), "scripts/google-sheets-output.json");
  const dryRun = args.includes("--dry-run") || args.includes("-d");

  try {
    await updateLessonUrlsFromJson(jsonFilePath, dryRun);
  } catch (error) {
    console.error("\n❌ Error:", error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

main();

